# See https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: npm
    allow:
      - dependency-type: production
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    allow:
      - dependency-type: development
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
