name: Setup fasm
author: stevenwdv
description: Set up the flat assembler compiler

inputs:
  edition:
    description: Edition to install; fasm1, fasmg, or fasmarm
    required: false
    default: fasm1
  version:
    description: Version of edition to install; e.g. 1.73.30, 1.73.*, or latest
    required: false
    default: latest
  download-unknown:
    description: Try to download unknown versions; one of never, secure, a BLAKE2b-512 hash, or insecure
    required: false
    default: never
  assume-dynamic-unchanged:
    description: Assume dynamic versions (FASMARM) do not change compared to the cache; true or false
    required: false
    default: 'false'
  set-include-envvar:
    description: Set INCLUDE environment variable to the INCLUDE folder of the fasm installation, if it was found; true or false
    required: false
    default: 'true'

outputs:
  path:
    description: Path to which binaries are installed (skipping any single root folder in the archive)
  edition:
    description: Installed edition, same as input
  version:
    description: Full installed version
  platform:
    description: Platform for which fasm was installed

runs:
  using: node16
  main: dist/setup.js

branding:
  icon: cpu
  color: blue
