name: Test action

on: [ push, pull_request ]

jobs:
  test-fasm1:
    name: Test install some fasm 1 versions
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        version: [ latest, 1.71.* ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Run setup-fasm
        id: fasm
        uses: ./
        with:
          edition: fasm1
          version: ${{ matrix.version }}
      - run: (fasm.x64 || fasm || fasm.o || fasm.exe) 2>&1 | grep -qF 'flat assembler  version ${{ steps.fasm.outputs.version }}'
        shell: sh

  test-fasmg:
    name: Test install latest fasm g version
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Run setup-fasm
        id: fasm
        uses: ./
        with:
          edition: fasmg
      - run: (fasmg.x64 || fasmg || fasmg.o || fasmg.exe) 2>&1 | grep -qF 'flat assembler  version g.${{ steps.fasm.outputs.version }}'
        shell: sh

  test-fasmarm:
    name: Test install latest FASMARM version
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Run setup-fasm
        id: fasm
        uses: ./
        with:
          edition: fasmarm
      - run: (fasmarm.x64 || fasmarm || fasmarm.o || fasmarm.exe) 2>&1 | grep -qF 'flat assembler for ARM'
        shell: sh
